"""init

Revision ID: 19515b927de4
Revises: 758cf018feff
Create Date: 2025-12-23 08:57:56.125282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '19515b927de4'
down_revision: Union[str, Sequence[str], None] = '758cf018feff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False))
    op.drop_column('chunks', 'vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=False))
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###
